
(function(){
'use strict';
var DEX='https://api.dexscreener.com',KEY='nightshift_v1',MAXPOS=3,MAXSIZE=35,LOSS=35,MINLIQ=10000,READY=78,EXIT_STOP=-12,BE_TRIGGER=15,T1=20,T2=40,T1_FRAC=.35,T2_FRAC=.35,TRAIL=15,STALE_MS=120000,TOKEN_PROGRAM='TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',TOKEN_2022_PROGRAM='TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb';
function $(s,r){return (r||document).querySelector(s)} function $$(s,r){return Array.prototype.slice.call((r||document).querySelectorAll(s))}
function day(){var d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function fresh(){return{positions:[],history:[],evaluations:{},snapshots:{},dismissed:{},daily:{date:day(),realized:0},candidates:[],filter:'all',size:10,last:0}}
var storageError='',storageBlocked=false,monitorBusy=false,activeReview=null,reviewEpoch=0;
function validAddress(a){if(typeof a!=='string'||!/^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(a))return false;var n=0n,alphabet='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';for(var i=0;i<a.length;i++)n=n*58n+BigInt(alphabet.indexOf(a[i]));var bytes=0;while(n>0n){bytes++;n>>=8n}var zeros=0;while(a[zeros]==='1')zeros++;return bytes+zeros===32}
function positive(n){return typeof n==='number'&&Number.isFinite(n)&&n>0}
function validState(x){
 if(!x||typeof x!=='object'||!Array.isArray(x.positions)||x.positions.length>MAXPOS||!Array.isArray(x.history)||!x.daily||typeof x.daily.date!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(x.daily.date)||!Number.isFinite(x.daily.realized))throw Error('Invalid state structure');
 var seen={};x.positions.forEach(function(p){if(!p||!validAddress(p.address)||seen[p.address]||!positive(p.amount)||p.amount>MAXSIZE||!positive(p.entry)||!positive(p.current)||!positive(p.opened)||typeof p.symbol!=='string')throw Error('Invalid position');seen[p.address]=true;Object.keys(p).forEach(function(k){if(typeof p[k]==='number'&&!Number.isFinite(p[k]))throw Error('Invalid position number')});['remainingPct','realizedPnl','dayRealized','peak','stopPct','lastPriceAt','dayBasis','entryLiquidity'].forEach(function(k){if(p[k]!=null&&typeof p[k]!=='number')throw Error('Invalid position field')});if(p.remainingPct!=null&&(p.remainingPct<0||p.remainingPct>1))throw Error('Invalid remaining size');if(p.dayBasis!=null&&!positive(p.dayBasis))throw Error('Invalid daily basis');['t1Hit','t2Hit','trailActive','stale'].forEach(function(k){if(p[k]!=null&&typeof p[k]!=='boolean')throw Error('Invalid exit flag')});});
 x.history.forEach(function(h){if(!h||typeof h.type!=='string'||typeof h.symbol!=='string'||typeof h.note!=='string'||!positive(h.time))throw Error('Invalid history')});
 ['evaluations','snapshots','dismissed'].forEach(function(k){if(!x[k]||typeof x[k]!=='object'||Array.isArray(x[k]))throw Error('Invalid '+k);Object.keys(x[k]).forEach(function(a){if(!validAddress(a))throw Error('Invalid token address');var v=x[k][a];if(k==='dismissed'){if(!positive(v))throw Error('Invalid dismissal')}else if(!v||typeof v!=='object'||!positive(k==='snapshots'?v.time:v.lastSeen))throw Error('Invalid record')})});
 return Object.assign(fresh(),{positions:x.positions,history:x.history,evaluations:x.evaluations,snapshots:x.snapshots,dismissed:x.dismissed,daily:x.daily,last:typeof x.last==='number'&&Number.isFinite(x.last)?x.last:0});
}
function decodeState(x){if(x&&x.version!==undefined){if(x.version!==2||x.app!=='NIGHTSHIFT')throw Error('Unsupported backup version');return validState(x.state)}return validState(x)}
function load(){try{var raw=localStorage.getItem(KEY);return raw?decodeState(JSON.parse(raw)):fresh()}catch(e){storageError='Saved data could not be loaded. Existing storage is preserved. Export recovery data or restore a valid backup before approving positions.';storageBlocked=true;return fresh()}}
var S=load(),busy=false,lastSwipe=null,sessionReviewed={};
function prune(){S.history=S.history.slice(0,250);var keep={};S.positions.forEach(function(p){keep[p.address]=true});['evaluations','snapshots','dismissed'].forEach(function(k){var keys=Object.keys(S[k]).sort(function(a,b){function time(v){return k==='dismissed'?v:k==='snapshots'?v.time:v.lastSeen}return time(S[k][b])-time(S[k][a])});keys.forEach(function(a,i){if(i>=1000&&!keep[a])delete S[k][a]})})}
function backup(){prune();return{app:'NIGHTSHIFT',version:2,exportedAt:new Date().toISOString(),state:{positions:S.positions,history:S.history,evaluations:S.evaluations,snapshots:S.snapshots,dismissed:S.dismissed,daily:S.daily,last:S.last}}}
function storageNotice(){var e=$('#storageStatus');e.textContent=storageError;e.classList.toggle('hidden',!storageError)}
function save(){if(storageBlocked){storageNotice();return false}try{localStorage.setItem(KEY,JSON.stringify(backup()));storageError='';storageNotice();return true}catch(e){storageError='Browser storage failed. Changes are only in memory. Export a backup now; new approvals are paused.';storageNotice();return false}}
function restoreBackup(text){if(text.length>5000000)throw Error('Backup exceeds 5 MB');var next=decodeState(JSON.parse(text));next.positions.forEach(function(p){p.stale=true;p.lastPriceAt=0});var previous=S;S=next;prune();try{localStorage.setItem(KEY,JSON.stringify(backup()))}catch(e){S=previous;throw Error('Restore could not be saved; current session preserved')}storageBlocked=false;storageError='';activeReview=null;reviewEpoch++;sessionReviewed={};lastSwipe=null;$('#backdrop').classList.add('hidden');storageNotice();render();monitorPositions()}
function ensurePosition(p){if(p.remainingPct==null)p.remainingPct=1;if(p.realizedPnl==null)p.realizedPnl=0;if(p.dayRealized==null)p.dayRealized=0;if(!p.peak)p.peak=p.current||p.entry;if(p.stopPct==null)p.stopPct=EXIT_STOP;if(p.t1Hit==null)p.t1Hit=false;if(p.t2Hit==null)p.t2Hit=false;if(p.trailActive==null)p.trailActive=false;if(p.lastPriceAt==null)p.lastPriceAt=0;if(p.stale==null)p.stale=false;return p}
function resetDay(){if(S.daily.date!==day()){S.daily={date:day(),realized:0};S.positions.forEach(function(p){ensurePosition(p);p.dayBasis=p.current||p.entry;p.dayRealized=0;p.dayDate=day()});save()}}
function get(url,opt){var c=new AbortController(),t=setTimeout(function(){c.abort()},9000);opt=opt||{};opt.signal=c.signal;opt.cache='no-store';opt.credentials='omit';opt.referrerPolicy='no-referrer';opt.redirect='error';return fetch(url,opt).then(function(r){if(!r.ok)throw Error(r.status);return r.json()}).finally(function(){clearTimeout(t)})}
var rpcClient=NightshiftData.createRpc(get);
function rpc(method,params){return rpcClient.request(method,params)}
function liquidityText(c){return c.m.liq===null?'UNKNOWN':money(c.m.liq)}
function candidateStatus(c){return !c.marketSupported?'UNSUPPORTED':c.hard?'REJECTED':!c.verified||c.m.liq===null?'AWAITING DATA':c.ready?'READY':'WATCHING'}
function renderDataHealth(){var e=$('#dataHealth');if(!e)return;var lines=Object.keys(rpcClient.health).map(function(k){var h=rpcClient.health[k];return new URL(k.split(' ')[0]).hostname+' · '+k.split(' ')[1]+': '+h.message});e.textContent='Scanner v2.1 · Browser-only · Pool markets: Raydium, Orca, Meteora, PumpSwap. '+(lines.length?lines.join(' | '):'RPC checks pending.');}
function discover(){return Promise.allSettled([get(DEX+'/token-profiles/latest/v1'),get(DEX+'/token-boosts/latest/v1')]).then(function(rs){var a=[];rs.forEach(function(r){if(r.status==='fulfilled'&&Array.isArray(r.value))r.value.forEach(function(x){if(x.chainId==='solana'&&validAddress(x.tokenAddress)&&a.indexOf(x.tokenAddress)<0)a.push(x.tokenAddress)})});return a.slice(0,40)})}
function pairs(addrs){addrs=addrs.filter(validAddress);if(!addrs.length)return Promise.resolve([]);var calls=[];for(var i=0;i<addrs.length;i+=25)calls.push(get(DEX+'/tokens/v1/solana/'+addrs.slice(i,i+25).join(',')).catch(function(){return[]}));return Promise.all(calls).then(function(x){return [].concat.apply([],x)})}
function choose(ps){var m={};(Array.isArray(ps)?ps:[]).forEach(function(p){if(!p||p.chainId!=='solana'||!p.baseToken||!validAddress(p.baseToken.address)||!positive(Number(p.priceUsd)))return;p._observedAt=Date.now();var a=p.baseToken.address,l=NightshiftData.liquidity(p),old=m[a],supported=NightshiftData.poolSupported(p),oldSupported=old&&NightshiftData.poolSupported(old);if(!old||(supported&&!oldSupported)||(supported===oldSupported&&(l===null?-1:l)>(NightshiftData.liquidity(old)===null?-1:NightshiftData.liquidity(old))))m[a]=p});return Object.keys(m).map(function(k){return m[k]})}
function isPump(p){return ((p.dexId||'')+' '+(Array.isArray(p.labels)?p.labels:[]).join(' ')+' '+(p.url||'')).toLowerCase().indexOf('pump')>=0}
function age(p){return p.pairCreatedAt?Math.max(0,(Date.now()-Number(p.pairCreatedAt))/60000):null}
function floor(size){return Math.max(MINLIQ,Number(size||10)*500)}
function metrics(p,old){var t=p.txns&&p.txns.m5||{},buys=+t.buys||0,sells=+t.sells||0,total=buys+sells,buy=total?buys/total:.5,v5=+(p.volume&&p.volume.m5)||0,v1=+(p.volume&&p.volume.h1)||0,pace=v1?v5/(v1/12):(v5?1:0),pc=+(p.priceChange&&p.priceChange.m5)||0,liq=+(p.liquidity&&p.liquidity.usd)||0,g=old&&old.liquidity?((liq-old.liquidity)/old.liquidity)*100:null;
var buyS=clamp(buy*100),volS=clamp(35+(pace-.7)*35),actS=clamp(total/40*100),priceS=clamp(50+pc*2.5),liqS=g===null?50:clamp(50+g*2.5);if(pc>35)priceS=clamp(100-(pc-35)*1.5,35,100);
return{buys:buys,sells:sells,total:total,buy:buy,v5:v5,v1:v1,pace:pace,pc:pc,liq:liq,g:g,activity:Math.round(actS),momentum:Math.round(volS*.32+buyS*.28+actS*.2+priceS*.12+liqS*.08)}}
function clamp(n,a,b){a=a===undefined?0:a;b=b===undefined?100:b;return Math.max(a,Math.min(b,isFinite(n)?n:a))}
function liqScore(l){return l>=150000?100:l>=75000?90:l>=50000?82:l>=25000?70:l>=17500?58:l>=10000?48:l>=5000?25:8}
function verify(a){var partial=null;if(!validAddress(a))return Promise.resolve({ok:false,coreOk:false,reason:'Invalid Solana address'});return Promise.allSettled([rpc('getAccountInfo',[a,{encoding:'jsonParsed',commitment:'finalized'}]),rpc('getTokenLargestAccounts',[a,{commitment:'finalized'}])]).then(function(results){if(results[0].status!=='fulfilled')throw results[0].reason;var x=[results[0].value,results[1].status==='fulfilled'?results[1].value:null];var account=x[0]&&x[0].value;if(!account)throw Error('Mint account not found');var owner=account.owner;if(owner!==TOKEN_PROGRAM&&owner!==TOKEN_2022_PROGRAM)throw Error('Address is not owned by a supported Solana token program');var data=account.data,parsed=data&&data.parsed;if(!parsed||parsed.type!=='mint'||!parsed.info)throw Error('RPC did not return a validated mint account');var info=parsed.info;if(!Object.prototype.hasOwnProperty.call(info,'mintAuthority')||!Object.prototype.hasOwnProperty.call(info,'freezeAuthority')||!Object.prototype.hasOwnProperty.call(info,'supply'))throw Error('Mint authority fields are incomplete');var supply;try{if(typeof info.supply!=='string'||!/^\d+$/.test(info.supply))throw Error();supply=BigInt(info.supply)}catch(e){throw Error('Mint supply could not be validated')}if(supply<=0n)throw Error('Mint supply is zero or invalid');partial={coreOk:true,mint:info.mintAuthority,freeze:info.freezeAuthority,top:null,program:owner===TOKEN_2022_PROGRAM?'Token-2022':'SPL Token'};if(results[1].status!=='fulfilled')throw results[1].reason;var holders=x[1]&&x[1].value;if(!Array.isArray(holders)||!holders.length)throw Error('Largest-holder data unavailable');var seen={},total=0n,sum=0n,amounts=[];holders.forEach(function(v,i){if(!v||!validAddress(v.address)||seen[v.address]||typeof v.amount!=='string'||!/^\d+$/.test(v.amount))throw Error('Invalid or duplicate holder data');seen[v.address]=true;var amount=BigInt(v.amount);if(amount>supply)throw Error('Holder amount exceeds supply');total+=amount;amounts.push(amount)});if(total>supply)throw Error('Reported holder total exceeds mint supply');amounts.sort(function(a,b){return a>b?-1:a<b?1:0});sum=amounts.slice(0,10).reduce(function(a,b){return a+b},0n);var top=Number(sum*10000n/supply)/100,program=owner===TOKEN_2022_PROGRAM?'Token-2022':'SPL Token';if(owner===TOKEN_2022_PROGRAM)return{ok:false,coreOk:true,mint:info.mintAuthority,freeze:info.freezeAuthority,top:top,program:program,reason:'Token-2022 extensions require additional review before NIGHTSHIFT can mark this token Ready'};return{ok:true,coreOk:true,mint:info.mintAuthority,freeze:info.freezeAuthority,top:top,program:program,reason:null}}).catch(function(e){return Object.assign({ok:false,coreOk:false,mint:null,freeze:null,top:null,program:null},partial||{},{reason:e&&e.message?e.message:'RPC safety verification failed'})})}
function evaluate(p,v){var m=metrics(p,S.snapshots[p.baseToken.address]),score=100,fails=[],warn=[],checks=[],a=age(p),verified=!!(v&&v.ok),coreVerified=!!(v&&v.coreOk),marketSupported=NightshiftData.poolSupported(p);m.liq=NightshiftData.liquidity(p);if(!marketSupported){m.liq=null;warn.push(NightshiftData.marketStatus(p)+': reserve-based assessment is not implemented. No approval.')}if(m.liq===null){warn.push('Liquidity UNKNOWN: usable pool liquidity was not supplied. Awaiting data; this is not a confirmed zero.')}else if(m.liq<floor(10)){score=0;fails.push('Liquidity is below the $10,000 hard floor.')}else if(m.liq<20000){score-=12;warn.push('Liquidity is only modestly above the desk minimum.')}
if(a!==null&&a<2){score-=10;warn.push('Pair is less than two minutes old.')}
checks.push(['Minimum liquidity',m.liq===null?'UNKNOWN':m.liq>=floor(10)?'PASS':'FAIL',m.liq===null?'unknown':m.liq>=floor(10)?'pass':'fail']);
if(coreVerified){if(v.mint!==null){score=0;fails.push('Mint authority is still enabled.')}if(v.freeze!==null){score=0;fails.push('Freeze authority is still enabled.')}checks.push(['Token program',v.program||'SUPPORTED','pass'],['Mint authority',v.mint===null?'DISABLED':'ENABLED',v.mint===null?'pass':'fail'],['Freeze authority',v.freeze===null?'DISABLED':'ENABLED',v.freeze===null?'pass':'fail'],['Top 10 accounts',v.top===null?'UNKNOWN':v.top.toFixed(1)+'% raw','unknown']);if(v.top!==null&&v.top>90){score-=22;fails.push('Raw top-10 concentration exceeds 90%; approval blocked until pool/vault attribution is supported.');warn.push('Raw top-10 account concentration is '+v.top.toFixed(1)+'%; pool/vault accounts are not excluded, so this is a concentration warning rather than a definitive insider reading.')}}else{checks.push(['Token program','UNVERIFIED','unknown'],['Mint authority','UNVERIFIED','unknown'],['Freeze authority','UNVERIFIED','unknown'],['Top 10 accounts','UNVERIFIED','unknown'])}
if(!verified)warn.push('Safety unverified: '+(v&&v.reason?v.reason:'RPC validation was unavailable')+'. This setup cannot become Ready.');
checks.push(['Deployer history','NOT VERIFIED IN V1','unknown'],['Insider / bundle clustering','NOT VERIFIED IN V1','unknown'],['Transfer restrictions',v&&v.program==='Token-2022'?'TOKEN-2022 REVIEW REQUIRED':'NOT VERIFIED IN V1','unknown']);
var coverage=Math.round(((m.liq===null?0:1)+(coreVerified?3+(v.top===null?0:1):0))/8*100),verifiedSafety=coreVerified?clamp(score):null;score=clamp(score);var ls=m.liq===null?0:liqScore(m.liq),opp=Math.round(score*.48+m.momentum*.42+ls*.10),hard=fails.length>0;if(hard)opp=Math.min(opp,35);if(!verified||m.liq===null||!marketSupported)opp=Math.min(opp,74);
var setup='PASS';if(marketSupported&&m.liq!==null&&!hard&&verified){if(opp>=84&&m.momentum>=85&&(a===null||a<=15))setup='SNIPE';else if(opp>=READY)setup='MOMENTUM';else if(opp>=72&&a!==null&&a>=30)setup='RUNNER'}
var reasons=[];if(m.pace>=1.35)reasons.push('5m volume is running at '+m.pace.toFixed(1)+'× its hourly pace.');if(m.buy>=.58&&m.total>=8)reasons.push('Buy pressure is '+Math.round(m.buy*100)+'% across recent transactions.');if(m.liq>=25000)reasons.push('Liquidity has reached '+money(m.liq)+'.');if(verified&&!v.mint&&!v.freeze)reasons.push('Mint and freeze authorities are disabled on-chain.');if(isPump(p))reasons.push('Pump-related market identified in the live feed.');if(!reasons.length)reasons.push('More evidence is still accumulating.');
return{address:p.baseToken.address,symbol:String(p.baseToken.symbol||'TOKEN').slice(0,80),name:String(p.baseToken.name||'Unknown token').slice(0,200),image:p.info&&p.info.imageUrl||'',dex:p.dexId||'unknown',source:isPump(p)?'Pump via DexScreener':'DexScreener',pump:isPump(p),price:+p.priceUsd||0,age:a,m:m,safety:verifiedSafety,coverage:coverage,observedAt:p._observedAt||Date.now(),liqScore:ls,opp:opp,setup:setup,marketSupported:marketSupported,ready:marketSupported&&m.liq!==null&&!hard&&verified&&opp>=READY,cleared:marketSupported&&m.liq!==null&&!hard&&verified&&score>=70,hard:hard,verified:verified,coreVerified:coreVerified,verifyReason:v&&v.reason||null,tokenProgram:v&&v.program||null,checks:checks,fails:fails,warn:warn,reasons:reasons,pair:p}}
function holdMinutes(setup){return setup==='SNIPE'?20:setup==='MOMENTUM'?90:setup==='RUNNER'?240:60}
function positionPnl(p){ensurePosition(p);var c=+(p.current||p.entry);return +(p.realizedPnl||0)+(+p.amount)*(+p.remainingPct)*(c/p.entry-1)}
function positionDayPnl(p){ensurePosition(p);var c=+(p.current||p.entry),b=+(p.dayBasis||p.entry);return +(p.dayRealized||0)+(+p.amount)*(+p.remainingPct)*((c-b)/p.entry)}
function stopPrice(p){ensurePosition(p);var base=p.entry*(1+p.stopPct/100);if(p.trailActive&&p.peak)return Math.max(base,p.peak*(1-TRAIL/100));return base}
function partialExit(p,fraction,label){ensurePosition(p);var f=Math.min(fraction,p.remainingPct);if(f<=0)return;var cur=+(p.current||p.entry),db=+(p.dayBasis||p.entry);p.realizedPnl+=(+p.amount)*f*(cur/p.entry-1);p.dayRealized+=(+p.amount)*f*((cur-db)/p.entry);p.remainingPct=Math.max(0,p.remainingPct-f);log('TARGET',p.symbol,label+' simulated: '+Math.round(f*100)+'% closed at '+price(cur)+' ('+pct((cur/p.entry-1)*100)+').')}
function exitTracked(p,reason){ensurePosition(p);var i=S.positions.indexOf(p);if(i<0)return;var cur=+(p.current||p.entry),total=positionPnl(p),dayp=positionDayPnl(p),ret=(cur/p.entry-1)*100;S.daily.realized+=dayp;S.positions.splice(i,1);log(total>=0?'WIN':'LOSS',p.symbol,'EXIT SIGNAL — '+reason+' · '+signed(total)+' total · '+pct(ret)+' final price move.');toast('EXIT SIGNAL — '+p.symbol+': '+reason)}
function evaluateExit(p,pair){ensurePosition(p);if(!pair||!positive(Number(pair.priceUsd)))return;if(!NightshiftData.poolSupported(pair)||NightshiftData.liquidity(pair)===null){p.stale=true;return}var cur=+pair.priceUsd,m=metrics(pair,S.snapshots[p.address]),liq=+(pair.liquidity&&pair.liquidity.usd)||0,ret=(cur/p.entry-1)*100,peakRet=(Math.max(p.peak||p.entry,cur)/p.entry-1)*100,held=(Date.now()-p.opened)/60000;p.current=cur;p.peak=Math.max(p.peak||cur,cur);p.lastPriceAt=Date.now();p.stale=false;p.latestMomentum=m.momentum;p.latestBuy=m.buy;p.latestLiquidity=liq;
if(peakRet>=BE_TRIGGER&&p.stopPct<0)p.stopPct=0;
if(cur<=stopPrice(p)){exitTracked(p,p.trailActive?'Trailing stop triggered':'Protective stop triggered');return}
if(liq<MINLIQ){exitTracked(p,'Liquidity fell below '+money(MINLIQ));return}
if(p.entryLiquidity&&liq<=p.entryLiquidity*.8){exitTracked(p,'Liquidity dropped 20%+ from entry');return}
if(m.total>=8&&m.buy<.35&&m.pc<=-7){exitTracked(p,'Momentum collapsed: '+Math.round(m.buy*100)+'% buys and '+pct(m.pc)+' over 5m');return}
if(!p.t1Hit&&ret>=T1){p.t1Hit=true;partialExit(p,T1_FRAC,'Target 1');p.stopPct=Math.max(p.stopPct,0)}
if(!p.t2Hit&&ret>=T2){p.t2Hit=true;partialExit(p,T2_FRAC,'Target 2');p.trailActive=true}
if(p.remainingPct<=.001){exitTracked(p,'Profit targets completed');return}
var maxHold=holdMinutes(p.setup),need=p.setup==='PASS'?5:10;if(held>=maxHold&&ret<need){exitTracked(p,'Time exit: '+Math.round(held)+'m held without sufficient follow-through');return}
p.exitSignal=p.trailActive?'TRAILING':p.stopPct>=0?'BREAKEVEN':'WATCHING'}
function stalePositions(){return S.positions.some(function(p){return p.stale||!p.lastPriceAt||Date.now()-p.lastPriceAt>STALE_MS})}
function refreshPositions(){if(!S.positions.length)return Promise.resolve();var tracked=S.positions.slice();return pairs(tracked.map(function(p){return p.address})).then(function(ps){var map={};choose(ps).forEach(function(x){map[x.baseToken.address]=x});tracked.forEach(function(p){if(S.positions.indexOf(p)<0)return;var pair=map[p.address];if(pair)evaluateExit(p,pair);else p.stale=true})}).catch(function(){tracked.forEach(function(p){p.stale=true})})}
function monitorPositions(){if(monitorBusy)return Promise.resolve();monitorBusy=true;resetDay();return refreshPositions().finally(function(){monitorBusy=false;save();render();if(activeReview){var c=S.candidates.find(function(x){return x.address===activeReview});if(c)drawReview(c)}})}
function approvalReason(c){if(storageBlocked||storageError)return 'Storage unavailable';if(stalePositions())return 'Position prices stale';if(halted())return 'Desk Halted';if(c&&!c.marketSupported)return 'Unsupported market';if(c&&c.m.liq===null)return 'Liquidity unknown';if(!c||!c.ready||c.opp<READY||c.hard||!c.verified)return 'Not Ready (78+ required)';if(!validAddress(c.address)||!positive(c.price)||!positive(c.observedAt)||Date.now()-c.observedAt>STALE_MS)return 'Candidate quote stale';if(!positive(S.size)||S.size>MAXSIZE)return 'Invalid size';if(S.positions.length>=MAXPOS)return 'Position limit reached';if(S.positions.some(function(p){return p.address===c.address}))return 'Already tracking';if(c.m.liq<floor(S.size))return 'Insufficient liquidity';return ''}
function safetyLabel(c){return c.safety===null?'Unknown':Math.round(c.safety)+'/100'}

function refresh(force){
 if(busy)return;if(!force&&Date.now()-S.last<7000)return;busy=true;$('#refresh').textContent='SCAN';resetDay();
 function publish(cs){S.candidates=cs.slice().sort(function(a,b){return b.opp-a.opp}).slice(0,50);update();render();if(activeReview){var current=S.candidates.find(function(c){return c.address===activeReview});if(current)drawReview(current)}}
 return discover().then(function(a){return pairs(a)}).then(function(ps){
   var list=choose(ps).filter(NightshiftData.poolSupported);
   if(list.length)return list;
   return get(DEX+'/latest/dex/search?q=SOL').then(function(x){return choose(x.pairs||[]).filter(NightshiftData.poolSupported)});
 }).then(function(list){
   var cs=list.map(function(p){return evaluate(p,null)}).sort(function(a,b){return b.m.momentum-a.m.momentum}),targets=cs.filter(function(c){return !c.hard&&c.m.liq!==null}).slice(0,8),seq=Promise.resolve();
   publish(cs);
   targets.forEach(function(c){seq=seq.then(function(){return verify(c.address).then(function(v){var i=cs.findIndex(function(x){return x.address===c.address});if(i>=0)cs[i]=evaluate(c.pair,v);publish(cs)})})});
   return seq;
 }).catch(function(){toast('Discovery unavailable. Position monitoring continues independently.')}).finally(function(){S.last=Date.now();save();render();busy=false;$('#refresh').textContent='LIVE'});
}

function update(){var map={};S.candidates.forEach(function(c){map[c.address]=c;var old=S.evaluations[c.address],first=old&&old.firstPrice||c.price,chg=first&&c.price?(c.price/first-1)*100:0;S.evaluations[c.address]={address:c.address,symbol:c.symbol,name:c.name,firstSeen:old&&old.firstSeen||Date.now(),lastSeen:Date.now(),firstPrice:first,latestPrice:c.price,peak:Math.max(old&&old.peak||chg,chg),trough:Math.min(old&&old.trough||chg,chg),opportunity:c.opp,safety:c.safety,momentum:c.m.momentum,decision:old&&old.decision||null,setup:c.setup};S.snapshots[c.address]={time:Date.now(),price:c.price,liquidity:c.m.liq}})}

function daily(){return +(S.daily.realized||0)+S.positions.reduce(function(t,p){return t+positionDayPnl(p)},0)}
function halted(){return daily()<=-LOSS}
function money(n){n=+n||0;return Math.abs(n)>=1000000?'$'+(n/1000000).toFixed(2)+'M':Math.abs(n)>=1000?'$'+(n/1000).toFixed(1)+'K':'$'+n.toFixed(2)}
function price(n){n=+n||0;return n>=1?'$'+n.toFixed(4):n>=.01?'$'+n.toFixed(5):n>=.0001?'$'+n.toFixed(7):'$'+n.toPrecision(5)}
function pct(n){n=+n||0;return(n>=0?'+':'')+n.toFixed(1)+'%'} function signed(n){n=+n||0;return(n>=0?'+':'-')+'$'+Math.abs(n).toFixed(2)}
function ago(m){return m===null?'age unknown':m<1?'<1m old':m<60?Math.round(m)+'m old':m<1440?(m/60).toFixed(1)+'h old':(m/1440).toFixed(1)+'d old'}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function safeImage(s){try{var u=new URL(s);return u.protocol==='https:'&&u.hostname==='cdn.dexscreener.com'&&!u.username&&!u.password&&(!u.port||u.port==='443')?u.href:''}catch(e){return ''}}
function avatar(c){var src=safeImage(c.image);return src?'<div class="avatar"><img src="'+esc(src)+'" referrerpolicy="no-referrer"></div>':'<div class="avatar">'+esc(c.symbol.charAt(0))+'</div>'}
function render(){storageNotice();renderDataHealth();S.positions.forEach(function(p){if(!p.lastPriceAt||Date.now()-p.lastPriceAt>STALE_MS)p.stale=true});var p=daily();$('#pnl').textContent=signed(p);$('#pnl').className=p<0?'bad':'good';$('#posCount').textContent=S.positions.length;$('#desk').textContent=halted()?'HALTED':stalePositions()||storageError?'PAUSED':'Live';$('#desk').className=halted()?'bad':'';$('#deskSub').textContent=halted()?'$35 daily loss limit':stalePositions()?'fresh position prices required':storageError?'storage needs attention':'risk rules active';
var visible=S.candidates.filter(function(c){return !(S.dismissed[c.address]>Date.now()-86400000)&&!sessionReviewed[c.address]}),best=visible.find(function(c){return c.ready})||visible[0];$('#scanned').textContent=S.candidates.length;$('#cleared').textContent=S.candidates.filter(function(c){return c.cleared}).length;$('#ready').textContent=S.candidates.filter(function(c){return c.ready}).length;$('#homePos').textContent=S.positions.length;$('#lossLeft').textContent=halted()?'HALTED':money(Math.max(0,LOSS-Math.max(0,-p)))+' remaining';
if(best){$('#deckReject').disabled=false;$('#deckReview').disabled=false;$('#deckReject').dataset.address=best.address;$('#deckReview').dataset.address=best.address;$('#heroDeck').innerHTML='<article class="card swipe-card" id="heroSwipeCard" data-swipe="'+esc(best.address)+'"><div class="swipe-stamp left" id="leftStamp">REJECT</div><div class="swipe-stamp right" id="rightStamp">REVIEW</div><div class="head"><span>Best Opportunity</span><span class="muted">'+candidateStatus(best)+'</span></div><div class="token">'+avatar(best)+'<div class="tokentxt"><h2>'+esc(best.symbol)+' <span class="pill">'+best.setup+'</span></h2><p>'+esc(best.name)+' · '+esc(best.source)+'</p></div><div class="score"><b>'+best.opp+'</b><small>SCORE</small></div></div><div class="grid"><div class="metric"><small>Verified Safety</small><b>'+safetyLabel(best)+'</b><small>Coverage '+best.coverage+'%</small></div><div class="metric"><small>Momentum</small><b>'+best.m.momentum+'</b></div><div class="metric"><small>Liquidity</small><b>'+best.liqScore+'</b></div><div class="metric"><small>Activity</small><b>'+best.m.activity+'</b></div></div><div class="signals">'+best.reasons.slice(0,2).map(function(x){return'<div class="sig">'+esc(x)+'</div>'}).join('')+(best.warn[0]?'<div class="sig warn">'+esc(best.warn[0])+'</div>':'')+'</div><button class="primary" data-review="'+esc(best.address)+'">Review →</button></article>'}else{$('#deckReject').disabled=true;$('#deckReview').disabled=true;delete $('#deckReject').dataset.address;delete $('#deckReview').dataset.address;$('#heroDeck').innerHTML='<article class="card swipe-card"><div class="head"><span>Best Opportunity</span><span class="muted">QUEUE CLEAR</span></div><p class="muted" style="text-align:center;padding:80px 8px">You reached the end of the current deck. Tap LIVE for fresh candidates or undo your last swipe.</p></article>'};
renderPositions();renderCandidates();renderHistory();bindReviews();bindSwipe()}
function renderPositions(){$('#posBadge').textContent=S.positions.length+'/3';if(!S.positions.length){$('#homePositions').innerHTML='<div class="row"><small>No tracked positions yet.</small></div>';$('#positionsList').innerHTML='<div class="notice"><p>Approve a reviewed setup to begin local tracking.</p></div>';return}
$('#homePositions').innerHTML=S.positions.slice(0,3).map(function(p){ensurePosition(p);var profit=positionPnl(p),r=(+(p.current||p.entry)/p.entry-1)*100;return'<div class="row"><div><strong>'+esc(p.symbol)+'</strong><small>'+Math.round(p.remainingPct*100)+'% remaining · '+(p.stale?'price stale':esc(p.exitSignal||'watching'))+'</small></div><b class="'+(profit>=0?'good':'bad')+'">'+signed(profit)+'</b></div>'}).join('');
$('#positionsList').innerHTML=S.positions.map(function(p){ensurePosition(p);var r=(+(p.current||p.entry)/p.entry-1)*100,profit=positionPnl(p),sp=stopPrice(p),badge=p.stale?'STALE':p.trailActive?'TRAILING':p.stopPct>=0?'BREAKEVEN':'WATCHING',bc=p.stale?'stale':p.trailActive||p.stopPct>=0?'hot':'';return'<div class="position"><div class="ptop"><strong>'+esc(p.symbol)+' <span class="exitbadge '+bc+'">'+badge+'</span></strong><b class="'+(profit>=0?'good':'bad')+'">'+signed(profit)+'</b></div><div class="pgrid"><div><small>ENTRY</small><b>'+price(p.entry)+'</b></div><div><small>CURRENT</small><b>'+price(p.current||p.entry)+'</b></div><div><small>RETURN</small><b>'+pct(r)+'</b></div><div><small>STOP</small><b>'+price(sp)+'</b></div><div><small>PEAK</small><b>'+price(p.peak||p.entry)+'</b></div><div><small>REMAINING</small><b>'+Math.round(p.remainingPct*100)+'%</b></div></div><div class="exitplan"><b>EXIT:</b> −12% stop · breakeven after +15% · 35% at +20% · 35% at +40% · final 30% trails peak by 15%. '+(p.stale?'Price is stale; no simulated exit will fire until a fresh quote arrives.':'Last quote '+Math.max(0,Math.round((Date.now()-p.lastPriceAt)/1000))+'s ago.')+'</div><button class="closepos" data-closepos="'+esc(p.address)+'">Close tracking manually</button></div>'}).join('');$$('[data-closepos]').forEach(function(b){b.onclick=function(){closePos(b.dataset.closepos)}})}

function renderCandidates(){var cs=S.candidates.slice();if(S.filter==='ready')cs=cs.filter(function(c){return c.ready});if(S.filter==='pump')cs=cs.filter(function(c){return c.pump});if(S.filter==='rejected')cs=cs.filter(function(c){return c.hard||c.opp<55});$('#candCount').textContent=S.candidates.length;$('#candidates').innerHTML=cs.slice(0,50).map(function(c){return'<div class="candidate" data-review="'+esc(c.address)+'"><div class="ctop"><div><strong>'+esc(c.symbol)+' <span class="pill">'+c.setup+'</span></strong><small>'+esc(c.source)+' · '+ago(c.age)+' · '+candidateStatus(c)+'</small></div><strong class="cscore">'+c.opp+'</strong></div><div class="cm"><div><small>VERIFIED SAFETY</small><b>'+safetyLabel(c)+'</b><small>Coverage '+c.coverage+'%</small></div><div><small>MOMENTUM</small><b>'+c.m.momentum+'</b></div><div><small>LIQUIDITY</small><b>'+liquidityText(c)+'</b></div><div><small>5M TX</small><b>'+c.m.total+'</b></div></div></div>'}).join('')||'<div class="notice"><p>No candidates match this view.</p></div>'}
function log(type,symbol,note){var item={type:type,symbol:symbol||'DESK',note:note,time:Date.now()};S.history.unshift(item);S.history=S.history.slice(0,250);return item.time}
function renderHistory(){$('#reviewed').textContent=Object.keys(S.evaluations).length;$('#approved').textContent=S.history.filter(function(h){return h.type==='APPROVED'}).length;$('#rejected').textContent=S.history.filter(function(h){return h.type==='REJECTED'}).length;$('#historyList').innerHTML=S.history.slice(0,100).map(function(h){return'<div class="hist '+esc(h.type)+'"><i class="dot"></i><div><strong>'+esc(h.symbol)+' · '+esc(h.type)+'</strong><span>'+esc(h.note)+'</span></div><span>'+new Date(h.time).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})+'</span></div>'}).join('')||'<div class="notice"><p>Desk decisions will appear here.</p></div>'}
function bindReviews(){document.querySelectorAll('[data-review]').forEach(function(b){b.onclick=function(e){e.stopPropagation();openReview(b.dataset.review)}})}
function showUndo(){var b=$('#undoSwipe');if(lastSwipe)b.classList.remove('hidden');else b.classList.add('hidden')}
function swipeToken(address,dir){var c=S.candidates.find(function(x){return x.address===address});if(!c)return;var prevDecision=S.evaluations[address]&&S.evaluations[address].decision||null,prevDismissed=S.dismissed[address]||null,logTime=null;if(dir==='left'){S.dismissed[address]=Date.now();if(S.evaluations[address])S.evaluations[address].decision='REJECTED';logTime=log('REJECTED',c.symbol,'Swiped left from the opportunity deck.');save()}else{sessionReviewed[address]=Date.now()}lastSwipe={address:address,dir:dir,prevDecision:prevDecision,prevDismissed:prevDismissed,logTime:logTime,symbol:c.symbol};showUndo();render();if(dir==='right')setTimeout(function(){openReview(address)},80)}
function actionFromArrow(dir){var b=dir==='left'?$('#deckReject'):$('#deckReview'),a=b&&b.dataset.address;if(!a)return;var card=$('#heroSwipeCard');if(card){card.style.transform='translateX('+(dir==='left'?-620:620)+'px) rotate('+(dir==='left'?-18:18)+'deg)';card.style.opacity='0';setTimeout(function(){swipeToken(a,dir)},180)}else swipeToken(a,dir)}
function undoLastSwipe(){if(!lastSwipe)return;var u=lastSwipe;if(u.dir==='left'){if(u.prevDismissed)S.dismissed[u.address]=u.prevDismissed;else delete S.dismissed[u.address];if(S.evaluations[u.address])S.evaluations[u.address].decision=u.prevDecision;if(u.logTime)S.history=S.history.filter(function(h){return h.time!==u.logTime});save()}else delete sessionReviewed[u.address];lastSwipe=null;showUndo();activeReview=null;reviewEpoch++;$('#backdrop').classList.add('hidden');go('home');render();toast('Last swipe undone.')}
function bindSwipe(){var card=$('#heroSwipeCard');if(!card)return;var sx=0,sy=0,dx=0,drag=false,moved=false;card.onpointerdown=function(e){if(e.target.closest('button'))return;sx=e.clientX;sy=e.clientY;dx=0;drag=true;moved=false;card.classList.add('dragging');try{card.setPointerCapture(e.pointerId)}catch(_){}};card.onpointermove=function(e){if(!drag)return;var x=e.clientX-sx,y=e.clientY-sy;if(Math.abs(y)>Math.abs(x)&&Math.abs(y)>12){drag=false;card.classList.remove('dragging');card.style.transform='';return}dx=x;moved=moved||Math.abs(dx)>7;var rot=dx/18;card.style.transform='translateX('+dx+'px) rotate('+rot+'deg)';var op=Math.min(1,Math.abs(dx)/95);$('#leftStamp').style.opacity=dx<0?op:0;$('#rightStamp').style.opacity=dx>0?op:0};card.onpointerup=function(){if(!drag)return;drag=false;card.classList.remove('dragging');if(Math.abs(dx)>=85){var dir=dx<0?'left':'right';card.style.transform='translateX('+(dx<0?-620:620)+'px) rotate('+(dx<0?-18:18)+'deg)';card.style.opacity='0';setTimeout(function(){swipeToken(card.dataset.swipe,dir)},180)}else{card.style.transform='';$('#leftStamp').style.opacity=0;$('#rightStamp').style.opacity=0;if(!moved)openReview(card.dataset.swipe)}};card.onpointercancel=function(){drag=false;card.classList.remove('dragging');card.style.transform='';if($('#leftStamp'))$('#leftStamp').style.opacity=0;if($('#rightStamp'))$('#rightStamp').style.opacity=0}}

function openReview(a){activeReview=a;var epoch=++reviewEpoch;var c=S.candidates.find(function(x){return x.address===a});if(!c)return;S.size=10;drawReview(c);$('#backdrop').classList.remove('hidden');if(c.marketSupported&&c.m.liq!==null&&!c.hard&&!c.verified&&!c._safetyChecking){c._safetyChecking=true;toast('Validating '+c.symbol+' safety…');verify(c.address).then(function(v){var i=S.candidates.findIndex(function(x){return x.address===a});if(i<0)return;var updated=evaluate(S.candidates[i].pair,v);updated._safetyChecking=false;updated._safetyChecked=true;S.candidates[i]=updated;update();save();if(activeReview===a&&epoch===reviewEpoch&&!$('#backdrop').classList.contains('hidden'))drawReview(updated);renderCandidates();bindReviews();if(updated.verified)toast(updated.symbol+' core safety verified.');else toast(updated.symbol+' safety remains unverified: '+(updated.verifyReason||'additional checks required'))})}}
function drawReview(c){var sizeOK=c.m.liq>=floor(S.size),disable=!!approvalReason(c),hold=holdMinutes(c.setup);$('#review').innerHTML='<div class="reviewtop"><div><h2>'+esc(c.symbol)+' <span class="pill">'+c.setup+'</span></h2><p>'+esc(c.name)+' · '+esc(c.source)+'</p></div><div class="score"><b>'+c.opp+'</b><small>SCORE</small></div></div><div class="grid"><div class="metric"><small>Verified Safety</small><b>'+safetyLabel(c)+'</b><small>Coverage '+c.coverage+'%</small></div><div class="metric"><small>Momentum</small><b>'+c.m.momentum+'</b></div><div class="metric"><small>Liquidity</small><b>'+c.liqScore+'</b></div><div class="metric"><small>Activity</small><b>'+c.m.activity+'</b></div></div><div class="notice"><p>Verification coverage: '+c.coverage+'% (8 checks). Deployer history, insider clustering and transfer restrictions remain UNKNOWN. Verified Safety measures only observed checks; it is not a probability of safety.</p></div><div class="block"><h4>Observed strengths</h4>'+c.reasons.map(function(x){return'<p class="reason">'+esc(x)+'</p>'}).join('')+'</div><div class="block warn"><h4>Concerns</h4>'+c.fails.concat(c.warn).map(function(x){return'<p class="reason">'+esc(x)+'</p>'}).join('')+'</div><div class="table">'+[['Price',price(c.price)],['Liquidity',liquidityText(c)],['Market assessment',candidateStatus(c)],['Quote age',Math.max(0,Math.round((Date.now()-c.observedAt)/1000))+'s'],['5m volume',money(c.m.v5)],['1h volume',money(c.m.v1)],['5m buys / sells',c.m.buys+' / '+c.m.sells],['Pair age',ago(c.age)],['DEX',c.dex]].map(function(x){return'<div class="tr"><span>'+esc(x[0])+'</span><b>'+esc(x[1])+'</b></div>'}).join('')+'</div><div class="checks">'+c.checks.map(function(x){return'<div class="check"><span>'+esc(x[0])+'</span><b class="'+x[2]+'">'+esc(x[1])+'</b></div>'}).join('')+'</div><div class="notice"><p><b>Safety status:</b> '+(c._safetyChecking?'Validating on-chain now…':c.verified?'Core SPL mint checks verified.':esc(c.verifyReason||'On-chain verification incomplete.'))+'</p></div><div class="notice"><p><b>Simulated exit plan:</b> −12% hard stop; breakeven protection after +15%; 35% target at +20%; 35% target at +40%; trailing 15% on the final 30%. Weak trades can time-exit after about '+hold+' minutes for this '+esc(c.setup)+' setup. No wallet order is placed.</p></div><div class="sizes"><button data-size="10" class="'+(S.size===10?'on':'')+'">$10</button><button data-size="20" class="'+(S.size===20?'on':'')+'">$20</button><button data-size="35" class="'+(S.size===35?'on':'')+'">$35</button></div><div class="actions"><button class="secondary" id="rejectBtn">Reject</button><button class="primary" id="approveBtn" '+(disable?'disabled':'')+'>'+(esc(approvalReason(c))||'Approve & Track')+'</button></div><p class="muted" style="text-align:center">Approval records and tracks only. It does not buy the token.</p>';
$$('[data-size]',$('#review')).forEach(function(b){b.onclick=function(){S.size=+b.dataset.size;drawReview(c)}});$('#rejectBtn').onclick=function(){if(lastSwipe&&lastSwipe.address===c.address){lastSwipe=null;delete sessionReviewed[c.address];showUndo()}S.dismissed[c.address]=Date.now();if(S.evaluations[c.address])S.evaluations[c.address].decision='REJECTED';log('REJECTED',c.symbol,c.fails[0]||'Manually rejected.');save();activeReview=null;reviewEpoch++;$('#backdrop').classList.add('hidden');render();toast(c.symbol+' rejected for 24 hours.')};$('#approveBtn').onclick=function(){approve(c)}}
function approve(c){c=S.candidates.find(function(x){return x.address===c.address});var reason=approvalReason(c);if(reason){toast(reason);return}if(lastSwipe&&lastSwipe.address===c.address){lastSwipe=null;showUndo()}S.positions.push({address:c.address,symbol:c.symbol,name:c.name,amount:Math.min(S.size,MAXSIZE),entry:c.price,current:c.price,opened:Date.now(),dayDate:day(),dayBasis:c.price,setup:c.setup,entryLiquidity:c.m.liq,remainingPct:1,realizedPnl:0,dayRealized:0,peak:c.price,stopPct:EXIT_STOP,t1Hit:false,t2Hit:false,trailActive:false,lastPriceAt:c.observedAt,stale:false,exitSignal:'WATCHING'});if(S.evaluations[c.address])S.evaluations[c.address].decision='APPROVED';log('APPROVED',c.symbol,money(S.size)+' simulated tracking started at '+price(c.price)+' with EXIT engine armed. No wallet transaction sent.');save();activeReview=null;reviewEpoch++;$('#backdrop').classList.add('hidden');render();toast(c.symbol+' tracking started — EXIT engine armed.')}

function closePos(a){resetDay();var i=S.positions.findIndex(function(p){return p.address===a});if(i<0)return;var p=S.positions[i];ensurePosition(p);if(p.stale||Date.now()-p.lastPriceAt>STALE_MS){toast('Fresh quote required before closing tracking.');return}var cur=+(p.current||p.entry),total=positionPnl(p),dayp=positionDayPnl(p);S.daily.realized+=dayp;S.positions.splice(i,1);log(total>=0?'WIN':'LOSS',p.symbol,'Manual tracking close · '+signed(total)+' total · '+pct((cur/p.entry-1)*100)+' final price move.');save();render();toast(p.symbol+' tracking closed manually.')}

function search(s){s=String(s||'').trim();if(!s)return;var req=/^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(s)?pairs([s]):get(DEX+'/latest/dex/search?q='+encodeURIComponent(s)).then(function(x){return x.pairs||[]});req.then(function(ps){var cs=choose(ps).slice(0,8).map(function(p){return evaluate(p,null)}),seq=Promise.resolve();cs.filter(function(c){return c.marketSupported&&c.m.liq!==null&&!c.hard}).slice(0,4).forEach(function(c){seq=seq.then(function(){return verify(c.address).then(function(v){var i=cs.findIndex(function(x){return x.address===c.address});cs[i]=evaluate(c.pair,v)})})});return seq.then(function(){var m={};S.candidates.concat(cs).forEach(function(c){m[c.address]=c});S.candidates=Object.keys(m).map(function(k){return m[k]}).sort(function(a,b){return b.opp-a.opp});update();save();render();toast(cs.length+' Solana market(s) added.')})}).catch(function(){toast('Search failed.')})}
function toast(t){var e=$('#toast');e.textContent=t;e.classList.remove('hidden');clearTimeout(e._t);e._t=setTimeout(function(){e.classList.add('hidden')},2700)}
function go(id){activeReview=null;reviewEpoch++;$('#backdrop').classList.add('hidden');$$('.view').forEach(function(v){v.classList.toggle('on',v.id===id)});$$('[data-nav]').forEach(function(b){b.classList.toggle('on',b.dataset.nav===id)});scrollTo(0,0)}
$('#refresh').onclick=function(){refresh(true)};$('#deckReject').onclick=function(){actionFromArrow('left')};$('#deckReview').onclick=function(){actionFromArrow('right')};$('#undoSwipe').onclick=undoLastSwipe;$('#close').onclick=function(){activeReview=null;reviewEpoch++;$('#backdrop').classList.add('hidden')};$('#reviewHome').onclick=function(){activeReview=null;reviewEpoch++;$('#backdrop').classList.add('hidden');go('home')};$('#backdrop').onclick=function(e){if(e.target===$('#backdrop')){activeReview=null;reviewEpoch++;$('#backdrop').classList.add('hidden')}};$$('[data-nav]').forEach(function(b){b.onclick=function(){go(b.dataset.nav)}});$$('[data-go]').forEach(function(b){b.onclick=function(){go(b.dataset.go)}});$$('.chip').forEach(function(b){b.onclick=function(){S.filter=b.dataset.filter;$$('.chip').forEach(function(x){x.classList.toggle('on',x===b)});renderCandidates();bindReviews()}});$('#searchForm').onsubmit=function(e){e.preventDefault();search($('#searchInput').value)};$('#export').onclick=function(){var payload=backup();if(storageBlocked){try{payload.recoveryRaw=localStorage.getItem(KEY)}catch(e){payload.recoveryError='Storage unavailable'}}var blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='nightshift-'+day()+'.json';a.click();setTimeout(function(){URL.revokeObjectURL(u)},500)};
$('#import').onclick=function(){$('#importFile').click()};$('#importFile').onchange=function(e){var f=e.target.files[0];if(!f)return;if(f.size>5000000){toast('Backup exceeds 5 MB');return}if(!confirm('Replace current local tracking and history with this backup? Export your current data first.'))return;var reader=new FileReader();reader.onload=function(){try{restoreBackup(reader.result);toast('Backup restored. Refreshing position prices.')}catch(err){toast('Restore failed: '+err.message)}};reader.onerror=function(){toast('Backup could not be read')};reader.readAsText(f);e.target.value=''};
S.positions.forEach(function(p){ensurePosition(p);p.stale=true});resetDay();render();monitorPositions();refresh(true);
setInterval(function(){if(!document.hidden)monitorPositions()},15000);
setInterval(function(){if(!document.hidden)refresh(true)},45000);
document.addEventListener('visibilitychange',function(){if(!document.hidden){S.positions.forEach(function(p){p.stale=true});render();monitorPositions();if(Date.now()-S.last>45000)refresh(true)}});

})();
