const { test } = require('node:test');
const assert = require('node:assert/strict');
const vm = require('node:vm');
const fs = require('node:fs');
const source = fs.readFileSync('app.js', 'utf8');
const A = 'So11111111111111111111111111111111111111112';
const B = '11111111111111111111111111111111';
const C = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA';
function harness(raw=null) {
 const elements = new Map(); let stored=raw, fail=false;
 const document = {hidden:false, querySelector(s){if(!elements.has(s))elements.set(s,{textContent:'',innerHTML:'',dataset:{},classList:{add(){},remove(){},toggle(){},contains(){return false}},querySelectorAll(){return []}});return elements.get(s)},querySelectorAll(){return []}};
 const ctx = vm.createContext({document,localStorage:{getItem(){return stored},setItem(k,v){if(fail)throw Error('quota');stored=v}},Date,URL,console,setTimeout(){return 1},clearTimeout(){},AbortController,scrollTo(){},fetch(){throw Error('Unexpected network')}});
 const cut = source.indexOf("$('#refresh').onclick=");
 vm.runInContext(source.slice(0,cut)+`globalThis.api={get S(){return S},set S(v){S=v},validAddress,choose,verify,evaluate,approve,drawReview,openReview,approvalReason,backup,decodeState,save,restoreBackup,monitorPositions,refreshPositions,safetyLabel,safeImage,avatar,stalePositions,positionDayPnl,partialExit, setRpc(f){rpc=f},setPairs(f){pairs=f},setBusy(v){busy=v},get storageBlocked(){return storageBlocked},get activeReview(){return activeReview}};})();`,ctx);
 return {api:ctx.api,ctx,elements,stored:()=>stored,fail(v){fail=v}};
}
function pair(a=A){return {chainId:'solana',baseToken:{address:a,symbol:'TEST',name:'Test'},priceUsd:'1',liquidity:{usd:200000},volume:{m5:10000,h1:20000},txns:{m5:{buys:95,sells:5}},priceChange:{m5:10},pairCreatedAt:Date.now()-600000};}
function verified(top=20){return {ok:true,coreOk:true,mint:null,freeze:null,top,program:'SPL Token'}}
function pos(a=A){return {address:a,symbol:'TEST',amount:10,entry:1,current:1,opened:Date.now(),lastPriceAt:Date.now(),stale:false}}
function rpcData(api,amounts=['20'],info={}){api.setRpc(async m=>m==='getAccountInfo'?{value:{owner:C,data:{parsed:{type:'mint',info:{supply:'100',mintAuthority:null,freezeAuthority:null,...info}}}}}:{value:amounts.map((amount,i)=>({address:[A,B,C][i],amount}))});}
test('below Ready is blocked by both UI and approval, including contradictory ready flag',()=>{const {api,elements}=harness();const c=api.evaluate(pair(),verified());c.opp=77;c.ready=true;api.S.candidates=[c];api.drawReview(c);assert.match(elements.get('#review').innerHTML,/id="approveBtn" disabled/);api.approve(c);assert.equal(api.S.positions.length,0);c.opp=90;c.ready=false;api.approve(c);assert.equal(api.S.positions.length,0)});
test('Ready approval succeeds once; duplicates and stale candidates rejected',()=>{const {api}=harness();const c=api.evaluate(pair(),verified());api.S.candidates=[c];assert.equal(api.approvalReason(c),'');api.approve(c);api.approve(c);assert.equal(api.S.positions.length,1);api.S.positions=[];c.observedAt=Date.now()-120001;api.approve(c);assert.equal(api.S.positions.length,0)});
test('unverified safety is Unknown and coverage explicitly partial',()=>{const {api}=harness();const c=api.evaluate(pair(),null);assert.equal(c.safety,null);assert.equal(api.safetyLabel(c),'Unknown');assert.equal(c.coverage,13);assert.ok(c.opp<=74);assert.equal(c.ready,false);const v=api.evaluate(pair(),verified());assert.equal(v.coverage,63);assert.equal(api.safetyLabel(v),'100/100')});
test('95% concentration cannot become Ready even with strong momentum',()=>{const {api}=harness();const c=api.evaluate(pair(),verified(95));assert.equal(c.ready,false);assert.equal(c.hard,true);assert.ok(c.opp<=35)});
test('holder sums, negative amounts, duplicates and missing authority fail closed',async()=>{const {api}=harness();for(const amounts of [['60','60'],['-1'],['101']]){rpcData(api,amounts);assert.equal((await api.verify(A)).ok,false)}rpcData(api,['20'],{mintAuthority:undefined}); // explicit undefined is not a disabled authority
 const c=api.evaluate(pair(),await api.verify(A));assert.equal(c.ready,false);
 rpcData(api,['20']);assert.equal((await api.verify(A)).ok,true);
 api.setRpc(async m=>m==='getAccountInfo'?{value:{owner:C,data:{parsed:{type:'mint',info:{supply:'100',freezeAuthority:null}}}}}:{value:[]});assert.equal((await api.verify(A)).ok,false);
});
test('stale prices block approval; monitoring runs while discovery is busy and executes stop',async()=>{const {api}=harness();const c=api.evaluate(pair(B),verified());api.S.candidates=[c];api.S.positions=[{...pos(),lastPriceAt:Date.now()-120001}];assert.match(api.approvalReason(c),/stale/);api.setBusy(true);api.setPairs(async()=>[{...pair(),priceUsd:'.8'}]);await api.monitorPositions();assert.equal(api.S.positions.length,0);assert.ok(api.S.daily.realized<0);assert.match(api.S.history[0].note,/Protective stop/)});
test('failed position lookup marks stale immediately; overlapping monitor calls are suppressed',async()=>{const {api}=harness();api.S.positions=[pos()];let resolve,calls=0;api.setPairs(()=>{calls++;return new Promise(r=>resolve=r)});const p=api.monitorPositions();await api.monitorPositions();assert.equal(calls,1);resolve([]);await p;assert.equal(api.stalePositions(),true)});
test('storage failure is visible and blocks approval; corrupt storage is preserved',()=>{const h=harness();h.fail(true);assert.equal(h.api.save(),false);assert.match(h.elements.get('#storageStatus').textContent,/storage failed/);assert.match(h.api.approvalReason(h.api.evaluate(pair(),verified())),/Storage/);const broken=harness('{broken');assert.equal(broken.api.storageBlocked,true);assert.equal(broken.api.save(),false);assert.equal(broken.stored(),'{broken')});
test('complete versioned backup roundtrip and bounded retention',()=>{const {api}=harness();api.S.positions=[pos()];api.S.evaluations[A]={lastSeen:Date.now()};api.S.snapshots[A]={time:Date.now(),price:1,liquidity:10000};api.S.dismissed[A]=Date.now();api.S.history=Array.from({length:300},()=>({type:'TEST',symbol:'TEST',note:'ok',time:Date.now()}));const b=api.backup();assert.equal(b.version,2);assert.equal(b.state.history.length,250);const round=api.decodeState(JSON.parse(JSON.stringify(b)));assert.deepEqual(JSON.parse(JSON.stringify(round.snapshots)),JSON.parse(JSON.stringify(b.state.snapshots)));assert.deepEqual(JSON.parse(JSON.stringify(round.dismissed)),JSON.parse(JSON.stringify(b.state.dismissed)));assert.throws(()=>api.decodeState({...b,version:99}));b.state.positions[0].address='\" onclick=\"evil';assert.throws(()=>api.decodeState(b))});
test('data maps retain at most 1000 plus open positions',()=>{const {api}=harness();for(let i=0;i<1100;i++)api.S.snapshots['test'+i]={time:i+1};api.S.positions=[pos()];api.S.snapshots[A]={time:1};api.backup();assert.equal(Object.keys(api.S.snapshots).length,1001);assert.ok(api.S.snapshots[A])});
test('address and image allowlists reject injection and external trackers',()=>{const {api}=harness();assert.equal(api.validAddress(A),true);assert.equal(api.validAddress('1'.repeat(44)),false);assert.equal(api.choose([pair('x\" onmouseover=\"alert(1)')]).length,0);assert.equal(api.safeImage('https://tracker.example/a'),'');assert.equal(api.safeImage('https://cdn.dexscreener.com.evil.com/a'),'');assert.equal(api.safeImage('https://cdn.dexscreener.com/a'),'https://cdn.dexscreener.com/a');assert.doesNotMatch(api.avatar({image:'javascript:alert(1)',symbol:'<img>'}),/<img/)});
test('late verification cannot overwrite another token review',async()=>{const {api,elements}=harness();const a=api.evaluate(pair(),null),b=api.evaluate(pair(B),verified());b.symbol='SECOND';api.S.candidates=[a,b];let release;const pending=new Promise(r=>release=r);api.setRpc(async m=>{await pending;return m==='getAccountInfo'?{value:{owner:C,data:{parsed:{type:'mint',info:{supply:'100',mintAuthority:null,freezeAuthority:null}}}}}:{value:[{address:C,amount:'20'}]}});api.openReview(A);api.openReview(B);release();await new Promise(setImmediate);assert.match(elements.get('#review').innerHTML,/SECOND/);assert.equal(api.activeReview,B)});
test('daily P&L uses original quantity after a day rollover',()=>{const {api}=harness();const p={...pos(),entry:1,current:1.5,dayBasis:2,remainingPct:1,dayRealized:0};assert.equal(api.positionDayPnl(p),-5);api.partialExit(p,.35,'test');assert.equal(api.positionDayPnl(p),-5)});
test('CSP has no inline script allowance or handlers',()=>{const html=fs.readFileSync('index.html','utf8');assert.match(html,/script-src 'self';/);assert.match(html,/name="referrer" content="no-referrer"/);assert.doesNotMatch(html,/\son\w+=/);assert.doesNotMatch(source,/ onerror="/)});
test('restore saves full state, invalidates quotes, and rolls back if persistence fails',async()=>{const h=harness();const b=h.api.backup();b.state.positions=[pos()];h.api.setPairs(async()=>[]);h.api.restoreBackup(JSON.stringify(b));assert.equal(h.api.S.positions.length,1);assert.equal(h.api.S.positions[0].stale,true);assert.equal(h.api.S.positions[0].lastPriceAt,0);await new Promise(setImmediate);const before=h.api.S;h.fail(true);assert.throws(()=>h.api.restoreBackup(JSON.stringify(b)),/could not be saved/);assert.equal(h.api.S,before)});
test('daily loss limit and Token-2022 continue blocking approval',async()=>{const {api}=harness();const c=api.evaluate(pair(),verified());api.S.daily.realized=-35;assert.equal(api.approvalReason(c),'Desk Halted');api.setRpc(async m=>m==='getAccountInfo'?{value:{owner:'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb',data:{parsed:{type:'mint',info:{supply:'100',mintAuthority:null,freezeAuthority:null}}}}}:{value:[{address:A,amount:'20'}]});assert.equal(api.evaluate(pair(),await api.verify(A)).ready,false)});
test('duplicate holder accounts fail validation',async()=>{const {api}=harness();api.setRpc(async m=>m==='getAccountInfo'?{value:{owner:C,data:{parsed:{type:'mint',info:{supply:'100',mintAuthority:null,freezeAuthority:null}}}}}:{value:[{address:A,amount:'20'},{address:A,amount:'20'}]});assert.equal((await api.verify(A)).ok,false)});
